
export const ADD_CART_ITEM ='ADD_CART_ITEM';
export const REMOVE_CART_ITEM ='REMOVE_CART_ITEM';
export const CHANGE_CART_ITEM_QTY ='CHANGE_CART_ITEM_QTY';
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";

